version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

      # 追記
  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

# 追記
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - db-store:/var/lib/mysql
#      - ./infra/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=laravel_local
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    ports:
    - 3306:3306

# phpMyAdmin
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
    - 8080:80

# 追記
volumes:
  db-store:

